CREATE TABLE IF NOT EXISTS countries (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO countries(name) VALUES
('Greece'),
('Germany'),
('United Kingdom'),
('France'),
('Italy'),
('Spain'),
('Ukraine'),
('Poland'),
('Russia'),
('Romania'),
('Netherlands'),
('Belgium'),
('Czech Republic'),
('Portugal'),
('Sweden'),
('Hungary'),
('Belarus'),
('Austria'),
('Serbia'),
('Switzerland'),
('Bulgaria'),
('Denmark'),
('Finland'),
('Slovakia'),
('Norway'),
('Ireland'),
('Croatia'), 
('Moldova'), 
('Bosnia and Herzegovina'),
('Albania'),
('Lithuania'),
('Slovenia'),
('Latvia'),
('Estonia'),
('Montenegro'),
('Luxembourg'),
('Malta'),
('Iceland');