CREATE TABLE IF NOT EXISTS users (
	username VARCHAR(64) NOT NULL,
	password VARCHAR(64) NOT NULL,
	email VARCHAR(64) NOT NULL,
	phone VARCHAR(64) NOT NULL,
	tin VARCHAR(64) NOT NULL,
	countryId INT NOT NULL,
	address VARCHAR(64) NOT NULL,
	validated BOOL,
	longitude FLOAT,
	latitude FLOAT,
	admin BOOL,
	name VARCHAR(64) NOT NULL,
	surname VARCHAR(64) NOT NULL,
	location VARCHAR(64) NOT NULL,
	sellerRating INT NOT NULL,
	bidderRating INT NOT NULL,
	lastAccessedMessages TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(countryId) REFERENCES countries(id),
	PRIMARY KEY (username)
);

INSERT INTO users VALUES (
'admin',
'admin',
'admin@mail.com',
'6969696969',
'165432100',
1,
'Home',
1,
0,
0,
1,
'Admin',
'Admin',
'Athens',
0,
0,
'2022-01-01 00:00:00');
